spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    #    jdbc-url: jdbc:mysql://localhost:3306/menudb
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

#mybatis:
#  mapper-locations: com/**/*.xml

